optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 1e-3
  betas: 
    - 0.9
    - 0.999

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR 
  step_size: 1
  gamma: 0.1

loss:
  _target_: losses.signal_loss.SignalLoss
  config:
    reduction: mean
    beta: 1.0

metrics:
  _target_: metrics.signal_metrics.SignalMetrics
  config:
    min: 0
    max: 1
    step: 0